DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRAND;

CREATE TABLE BRAND (
BRAND INT PRIMARY KEY); 

CREATE TABLE PRICES (
BRAND_ID INT,
 START_DATE TIMESTAMP(6),
  END_DATE TIMESTAMP(6),
  PRICE_LIST INT,
  PRODUCT_ID INT,
  PRIORITY INT,
  PRICE DOUBLE,
  CURRENCY VARCHAR,
  BRAND INT,
 FOREIGN KEY (BRAND) REFERENCES BRAND);
 
